<a href="https://colab.research.google.com/github/hjw11223/Data-minig/blob/main/NumPy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy

* Numerical Python의 약자

* 다양한 수학 연산과 다차원 데이터를 쉽게 다루기 위한 파이썬 라이브러리

* Numpy는 ndarray라고 하는 특별한 객체를 사용
    + 리스트와 달리 고정된 크기를 갖음
    + 같은 타입의 데이터만 저장 가능

* ndarray는 python 리스트에서 지원하지 않는 다양한 기능들을 지원
    + 효율적으로 코드 작성 가능
    + 더 빠른 속도

In [ ]:
import numpy as np
np.__version__

'1.21.6'



---



# 배열 생성

## 리스트로 배열 만들기
![1.2 Array.png](https://drive.google.com/uc?id=1EKPVGuDQinETf6XkcKFYaQfqp5P2oklE)

In [ ]:
a1 = np.array([1, 2, 3, 4, 5])
print(a1)
print(type(a1))
print(a1.shape)
print(a1[0], a1[1], a1[2])

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1 2 3


In [ ]:
a2 = np.array([[1,2,3],[4,5,6]])
print(a2)
print(a2.shape)
print(a2[0,0], a2[1,1])

[[1 2 3]
 [4 5 6]]
(2, 3)
1 5


In [ ]:
a3 = np.array([[[1, 2, 3, 4], [4, 5, 6, 7], [9, 0, 1, 2]],
                [[3, 4, 5, 6], [7, 8, 9, 0], [1, 2, 3, 4]]
               ])
print(a3)
print(a3.shape)

[[[1 2 3 4]
  [4 5 6 7]
  [9 0 1 2]]

 [[3 4 5 6]
  [7 8 9 0]
  [1 2 3 4]]]
(2, 3, 4)


## 배열 생성 및 초기화

* `zeros()`: 모든 요소를 0으로 초기화

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

* `ones()`: 모든 요소를 1로 초기화

In [ ]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

* `full()`: 모든 요소를 지정한 값으로 초기화

In [ ]:
np.full((2,3), 1.23)

array([[1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23]])

* `eye()`: 단위행렬(identity matrix) 생성
  + 주대각선의 원소가 모두 1이고 나머지 원소는 모두 0인 정사각 행렬

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

* `tri()`: 삼각행렬 생성

In [ ]:
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

* `empty()`: 초기화되지 않은 배열 생성
  + 초기화가 없어서 배열 생성비용 저렴하고 빠름
  + 초기화되지 않아서 기존 메모리 위치에 존재하는 값이 있음

In [ ]:
np.empty(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

* `_like()`: 지정된 배열과 shape가 같은 행렬 생성
  + `np.zeros_like()`
  + `np.ones_like()`
  + `np.full_like()`
  + `np.empty_like()`

In [ ]:
print(a1)
np.zeros_like(a1)

[1 2 3 4 5]


array([0, 0, 0, 0, 0])

In [ ]:
print(a2)
np.ones_like(a2)

[[1 2 3]
 [4 5 6]]


array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
print(a3)
np.full_like(a3, 10)

[[[1 2 3 4]
  [4 5 6 7]
  [9 0 1 2]]

 [[3 4 5 6]
  [7 8 9 0]
  [1 2 3 4]]]


array([[[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]],

       [[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]]])

## 생성한 값으로 배열 생성

* `arange()`: 정수 범위로 배열 생성

In [ ]:
np.arange(0, 30, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

* `linspace()`: 범위 내에서 균등 간격의 배열 생성

In [ ]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## 랜덤값으로 배열 생성

| 함수 | 설명 |
|------|------|
| `seed` | 난수 발생을 위한 시드(seed) 지정 |
| `permutation` | 순서를 임의로 바꾸거나 임의의 순열 반환 |
| `shuffle` | 리스트나 배열의 순서를 뒤섞음 |
| `random` | 랜덤한 수의 배열 생성 |
| `rand` | 균등분포에서 표본 추출 |
| `randint` | 주어진 최소/최대 범위의 난수 추출 |
| `randn` | 표준편차가 1, 평균값 0인 정규분포의 표본 추출 |
| `binomial` | 이항분포에서 표본 추출 |
| `normal` | 정규분포(가우시안)에서 표본 추출 |
| `beta` | 베타분포에서 표본 추출 |
| `chisquare` | 카이제곱분포에서 표본 추출 |
| `gamma` | 감마분포에서 표본 추출 |
| `uniform` | 균등(0, 1)분포에서 표본 추출 |

* `random.random()`: 랜덤한 수의 배열 생성

In [ ]:
np.random.random((3,3))

array([[0.35235801, 0.33527557, 0.29519376],
       [0.59583733, 0.90653244, 0.68726548],
       [0.33821538, 0.13142012, 0.10787547]])

* `random.randint()`: 일정 구간의 랜덤 정수의 배열 생성

In [ ]:
np.random.randint(0, 10, (3,3))

array([[7, 4, 7],
       [2, 1, 1],
       [0, 1, 6]])

* `random.normal()`: 정규분포(normal distribution)를 고려한 랜덤한 수의 배열 생성
* 평균=0, 표준편차=1, 3 x 3 배열

In [ ]:
np.random.normal(0, 1, (3,3))

array([[ 1.89632929,  0.12696048,  1.29972332],
       [-0.81576109, -0.74237323,  1.34538663],
       [ 0.17881494,  0.70739359, -0.51729794]])

* `random.rand()`: 균등분포(uniform distribution)를 고려한 랜덤한 수의 배열 생성

In [ ]:
np.random.rand(3,3)

array([[0.52437438, 0.05664569, 0.99847127],
       [0.71594751, 0.97220701, 0.73342806],
       [0.5841365 , 0.34936384, 0.52788816]])

* `random.randn()`: 표준 정규 분포(standard normal distribution)를 고려한 랜덤한 수의 배열 생성

In [ ]:
np.random.randn(3,3)

array([[ 0.35453631, -0.29840889,  0.33357831],
       [ 0.27985278,  0.55576783,  0.77896425],
       [-0.37090552, -0.91854451, -0.30744496]])

## 표준 데이터 타입

| 데이터 타입	    | 설명 |
|---------------|-------------|
| ``bool_``     | 바이트로 저장된 불리언(Boolean)으로 True 또는 False 값을 가짐 |
| ``int_``      | 기본 정수(Integer) 타입 | 
| ``intc``      | C 언어에서 사용되는 ``int``와 동일 (일반적으로 ``int32`` 또는 ``int64``) | 
| ``intp``      | 인덱싱에 사용되는 정수 (C 언어에서 ``ssize_t``와 동일; 일반적으로 ``int32`` 또는 ``int64``) | 
| ``int8``      | 바이트(Byte) (-128 ~ 127) | 
| ``int16``     | 정수 (-32768 ~ 32767) |
| ``int32``     | 정수 (-2147483648 ~ 2147483647) |
| ``int64``     | 정수(-9223372036854775808 ~ 9223372036854775807) | 
| ``uint8``     | 부호 없는 정수 (0 ~ 255) | 
| ``uint16``    | 부호 없는 정수 (0 ~ 65535) | 
| ``uint32``    | 부호 없는 정수 (0 ~ 4294967295) | 
| ``uint64``    | 부호 없는 정수 (0 ~ 18446744073709551615) |  
| ``float16``   | 반정밀 부동 소수점(Half precision float): 부호 비트, 5비트 지수, 10비트 가수 | 
| ``float32``   | 단정밀 부동 소수점(Single precision float): 부호 비트, 8비트 지수, 23비트 가수| 
| ``float64``   | 배정밀 부동 소수점(Double precision float): 부호 비트, 11비트 지수, 52비트 가수 |
| ``float_``    | ``float64``를 줄여서 표현 |
| ``complex64`` | 복소수(Complex number), 두 개의 32비트 부동 소수점으로 표현 | 
| ``complex128``| 복소수, 두 개의 64비트 부동 소수점으로 표현| 
| ``complex_``  | ``complex128``를 줄여서 표현 | 

In [ ]:
np.zeros(20, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
np.full((3,3), 1, dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])



---



# 배열 조회

## 배열 속성 정보

In [ ]:
def array_info(array):
  print(array)
  print("ndim:", array.ndim)
  print("shape:", array.shape)
  print("dtype:", array.dtype)
  print("size:", array.size)
  print("itemsize:", array.itemsize)
  print("nbytes:", array.nbytes)
  print("strides:", array.strides)

In [ ]:
array_info(a1)

[1 2 3 4 5]
ndim: 1
shape: (5,)
dtype: int64
size: 5
itemsize: 8
nbytes: 40
strides: (8,)


In [ ]:
array_info(a2)

[[1 2 3]
 [4 5 6]]
ndim: 2
shape: (2, 3)
dtype: int64
size: 6
itemsize: 8
nbytes: 48
strides: (24, 8)


In [ ]:
array_info(a3)

[[[1 2 3 4]
  [4 5 6 7]
  [9 0 1 2]]

 [[3 4 5 6]
  [7 8 9 0]
  [1 2 3 4]]]
ndim: 3
shape: (2, 3, 4)
dtype: int64
size: 24
itemsize: 8
nbytes: 192
strides: (96, 32, 8)


## 인덱싱(Indexing)

In [ ]:
print(a1)
print(a1[0])
print(a1[2])
print(a1[-1])
print(a1[-2])

[1 2 3 4 5]
1
3
5
4


In [ ]:
print(a2)
print(a2[0, 0])
print(a2[0, 2])
print(a2[1, -1])

[[1 2 3]
 [4 5 6]]
1
3
6


In [ ]:
print(a3)
print(a3[0, 0, 0])
print(a3[1, 1, 1])
print(a3[0, -1, -1])

[[[1 2 3 4]
  [4 5 6 7]
  [9 0 1 2]]

 [[3 4 5 6]
  [7 8 9 0]
  [1 2 3 4]]]
1
8
2


## 슬라이싱(Slicing)

* 슬라이싱 구문: `a[start:stop:step]`
* 기본값: start=0, stop=ndim, step=1

In [ ]:
print(a1)
print(a1[0:2])
print(a1[1:])
print(a1[:3])
print(a1[::2])
print(a1[::-1])

[1 2 3 4 5]
[1 2]
[2 3 4 5]
[1 2 3]
[1 3 5]
[5 4 3 2 1]


In [ ]:
print(a2)
print(a2[1])
print(a2[1, :])
print(a2[:1, :2])
print(a2[1:, ::-1])
print(a2[::-1, ::1])
print(a2[::-1, ::-1])

[[1 2 3]
 [4 5 6]]
[4 5 6]
[4 5 6]
[[1 2]]
[[6 5 4]]
[[4 5 6]
 [1 2 3]]
[[6 5 4]
 [3 2 1]]


## 불리언 인덱싱(Boolean Indexing)

* 배열 각 요소의 선택 여부를 불리언(True or False)로 지정
* True 값인 인덱스의 값만 조회

In [ ]:
print(a1)
bi = [False,  True, True, False, True]
print(a1[bi])
bi = [True, False, True, True, False]
print(a1[bi])

[1 2 3 4 5]
[2 3 5]
[1 3 4]


In [ ]:
print(a2)
bi = np.random.randint(0, 2, (2,3), dtype=bool)
print(bi)
print(a2[bi])

[[1 2 3]
 [4 5 6]]
[[False False  True]
 [False  True  True]]
[3 5 6]




---



# 배열 값 삽입/수정/삭제/복사

## 배열 값 삽입

* `insert()`: 배열의 특정 위치에 값 삽입
* axis를 지정하지 않으면 1차원 배열로 변환
* 추가할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [ ]:
print(a1)
b1 = np.insert(a1, 0, 10)
print(b1)
c1 = np.insert(a1, 2, 10)
print(c1)

[1 2 3 4 5]
[10  1  2  3  4  5]
[ 1  2 10  3  4  5]


In [ ]:
print(a2)
b2 = np.insert(a2, 1, 10, axis=0)
print(b2)
c2 = np.insert(a2, 1, 10, axis=1)
print(c2)

[[1 2 3]
 [4 5 6]]
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]]
[[ 1 10  2  3]
 [ 4 10  5  6]]


## 배열 값 수정

* 배열의 인덱싱으로 접근하여 값 수정

In [ ]:
a1[0] = 11
a1[1] = 22
a1[2] = 33
print(a1)

[11 22 33  4  5]


In [ ]:
a1[:2] = 9
print(a1)

[ 9  9 33  4  5]


In [ ]:
i = np.array([1, 3, 4])
a1[i] = 0
print(a1)

[ 9  0 33  0  0]


In [ ]:
a2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a2)
a2[0, 0] = 11
a2[1, 1] = 22
print(a2)
a2[0] = 1
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11  2  3]
 [ 4 22  6]
 [ 7  8  9]]
[[ 1  1  1]
 [ 4 22  6]
 [ 7  8  9]]


In [ ]:
a2[1:, 2] = 19
print(a2)

[[ 1  1  1]
 [ 4 22 19]
 [ 7  8 19]]


## 배열 값 삭제

* `delete()`: 배열의 특정 위치에 값 삭제
* axis를 지정하지 않으면 1차원 배열로 변환
* 삭제할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [ ]:
a1 =np.array([1,2,3,4,5])
print(a1)

[1 2 3 4 5]


In [ ]:
b1 = np.delete(a1, 1)
print(b1)
print(a1)

[1 3 4 5]
[1 2 3 4 5]


In [ ]:
a2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
b2 = np.delete(a2, 1, axis=0)
print(b2)

[[1 2 3]
 [7 8 9]]


In [ ]:
c2 = np.delete(a2,1, axis=1)
print(c2)

[[1 3]
 [4 6]
 [7 9]]


## 배열 복사

* 리스트 자료형과 달리 배열의 슬라이스는 복사본이 아님

In [ ]:
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
a2_sub = a2[:2, :2]
print(a2_sub)

[[1 2]
 [4 5]]


In [ ]:
a2_sub[:, 1]= 0
print(a2_sub)
print(a2)

[[1 0]
 [4 0]]
[[1 0 3]
 [4 0 6]
 [7 8 9]]



* `copy()`: 배열이나 하위 배열 내의 값을 명시적으로 복사

In [ ]:
a2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
a2_sub_copy=a2[:2, :2].copy()
print(a2_sub_copy)

[[1 2]
 [4 5]]


In [ ]:
a2_sub_copy[:,1] = 0
print(a2_sub_copy)
print(a2)

[[1 0]
 [4 0]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]




---



# 배열 변환

## 배열 전치 및 축 변경

In [ ]:
print(a2.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
print(a2.swapaxes(1,0))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


## 배열 재구조화


* `reshape()`: 배열의 형상을 변경

In [ ]:
n1 = np.arange(1, 10)
print(n1)
print(n1.reshape(3,3))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


* `newaxis()`: 새로운 축 추가. 한 차원 증가

In [ ]:
print(n1)

[1 2 3 4 5 6 7 8 9]


In [ ]:
print(n1[np.newaxis, 2:5])
print(n1[2:5, np.newaxis])

[[3 4 5]]
[[3]
 [4]
 [5]]


## 배열 크기 변경

* `resize()`: 배열 크기 변경
* element의 수가 같으면, 배열 모양만 변경
* element의 sequence는 유지됨

In [ ]:
n2 = np.random.randint(0, 10, (2, 5))
print(n2)

[[7 0 1 1 6]
 [7 5 0 6 8]]


In [ ]:
n2.resize((5,2))
print(n2)

[[7 0]
 [1 1]
 [6 7]
 [5 0]
 [6 8]]


* resize 크기가 원본 배열보다 크면, 남은 공간은 0으로 채워짐

In [ ]:
n2.resize((5,5), refcheck=False)
print(n2)

[[7 0 1 1 6]
 [7 5 0 6 8]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [ ]:
np.resize(n2, (5,5))

array([[7, 0, 1, 1, 6],
       [7, 5, 0, 6, 8],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

* resize 크기가 원본 배열보다 작으면, 기본 값은 삭제됨

In [ ]:
n2.resize(3,3, refcheck=False)
print(n2)

[[7 0 1]
 [1 6 7]
 [5 0 6]]


## 배열 추가

* `append()`: 배열의 끝에 값 추가

In [ ]:
a2 = np.arange(1,10).reshape(3,3)
b2 = np.arange(10,19).reshape(3,3)
print(a2)
print(b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


* axis 지정이 없으면 1차원 배열 형태로 변형되어 결합

In [ ]:
c2 = np.append(a2, b2)
print(c2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


* axis를 0으로 지정 : 행 방향 결합

In [ ]:
c2 = np.append(a2, b2, axis=0)
print(c2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


* axis를 1로 지정 : 열 방향 결합

In [ ]:
c2 = np.append(a2, b2, axis=1)
print(c2)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


## 배열 분할

* `split()`: 배열 분할

In [ ]:
a1 = np.arange(11,21)
print(a1)

[11 12 13 14 15 16 17 18 19 20]


In [ ]:
b1, c1 = np.split(a1, [5])
print(b1, c1)

[11 12 13 14 15] [16 17 18 19 20]


In [ ]:
b1, c1, d1, e1, f1 = np.split(a1, [2, 4, 6, 8])
print(b1, c1, d1, e1, f1)

[11 12] [13 14] [15 16] [17 18] [19 20]


* `vsplit()`: 수직(y축) 분할. 행 분할

In [ ]:
a2 = np.arange(1, 10).reshape(3,3)
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
b2, c2 =np.vsplit(a2, [2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]]
[[7 8 9]]


* `hsplit()`: 수평(x축) 분할. 열 분할

In [ ]:
b2, c2 =np.hsplit(a2, [2])
print(b2)
print(c2)

[[1 2]
 [4 5]
 [7 8]]
[[3]
 [6]
 [9]]




---



# 배열 연산

* NumPy의 배열 연산은 벡터화(vectorized) 연산을 사용
* 일반적으로 NumPy의 범용 함수(universal functions)를 통해 구현
* 배열 요소에 대한 반복적인 계산을 효율적으로 수행

## 브로드캐스팅(Broadcasting)

![1.3 Broadcasting.png](https://drive.google.com/uc?id=1iDTSzbR5GILf1-A7aTfNssG_IF6UZAD2)

In [ ]:
a1 = np.array([1, 2, 3])
print(a1)
print(a1 + 5)

[1 2 3]
[6 7 8]


In [ ]:
a2 = np.arange(1, 10).reshape(3,3)
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(a1+a2)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [ ]:
b2 = np.array([1, 2, 3]).reshape(3, 1)
print(b2)

[[1]
 [2]
 [3]]


In [ ]:
print(a1+b2)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


## 산술 연산(Arithmetic Operators)

| 연산자	      | 범용 함수           | 설명        |
|---------------|---------------------|-------------|
|``+``          |``np.add``           | 덧셈        |
|``-``          |``np.subtract``      | 뺄셈        |
|``-``          |``np.negative``      | 단항 음수  |
|``*``          |``np.multiply``      | 곱셈        |
|``/``          |``np.divide``        | 나눗셈      |
|``//``         |``np.floor_divide``  | 나눗셈 내림 |
|``**``         |``np.power``         | 지수 연산   |
|``%``          |``np.mod``           | 나머지 연산 |


In [ ]:
a1 = np.arange(1,10)
print(a1)

[1 2 3 4 5 6 7 8 9]


In [ ]:
print(a1+1)
print(np.add(a1, 10))

[ 2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19]


In [ ]:
a1 = np.arange(1, 10)
b1 = np.random.randint(1, 10 , size=9)
print(a1)
print(b1)

[1 2 3 4 5 6 7 8 9]
[2 8 8 1 5 8 2 2 9]


In [ ]:
print(a1+b1)
print(np.add(a1,b1))

[ 3 10 11  5 10 14  9 10 18]
[ 3 10 11  5 10 14  9 10 18]


## 절대값 함수(Absolute Function)

* `absolute()`, `abs()`:내장된 절대값 함수

In [ ]:
a1 = np.random.randint(-10, 10, size=5)
print(a1)
print(np.absolute(a1))
print(abs(a1))

[ 4 -4  5 -7 -1]
[4 4 5 7 1]
[4 4 5 7 1]


## 제곱/제곱근 함

* `square`, `sqrt`:제곱, 제곱근 함수

In [ ]:
print(np.square(a1))
print(np.sqrt(a1))

[16 16 25 49  1]
[2.                nan 2.23606798        nan        nan]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


## 지수와 로그 함수(Exponential and Log Function)

In [ ]:
a1 = np.random.randint(1, 10, size = 5)
print(a1)
print(np.exp(a1)) # e^n
print(np.exp2(a1)) # 2^n
print(np.power(a1, 2))

[7 9 8 3 7]
[1096.63315843 8103.08392758 2980.95798704   20.08553692 1096.63315843]
[128. 512. 256.   8. 128.]
[49 81 64  9 49]


In [ ]:
print(np.log(a1))
print(np.log2(a1))
print(np.log10(a1))

[1.94591015 2.19722458 2.07944154 1.09861229 1.94591015]
[2.80735492 3.169925   3.         1.5849625  2.80735492]
[0.84509804 0.95424251 0.90308999 0.47712125 0.84509804]


## 집계함수(Aggregate Functions)

| 함수	      | NaN안전모드           | 설명        |
|---------------|---------------------|-------------|
|``np.sum``        |``np.nansum``        | 요소의 합 계산 |
|``np.cumsum``     |``np.nancumsum``     | 요소의 누적 합 |
|``np.diff``       | N/A                 | 요소의 차분 |
|``np.prod``       |``np.nanprod``       | 요소의 곱 계산 |
|``np.cumprod``    |``np.nancumprod``    | 요소의 누적 곱 |
|``np.dot``        | N/A                 | 점 곱(dot product) |
|``np.matmul``     | N/A                 | 행렬 곱 |
|``np.tensordot``  | N/A                 | 텐서곱(tensor product) |
|``np.cross``      | N/A                 | 벡터곱(vector product) |
|``np.inner``      | N/A                 | 내적(inner product) |
|``np.outer``      | N/A                 | 외적(outer product) |
|``np.mean``       |``np.nanmean``       | 요소의 평균 계산 |
|``np.std``        |``np.nanstd``        | 표준 편차 계산 |
|``np.var``        |``np.nanvar``        | 분산 계산 |
|``np.min``        |``np.nanmin``        | 최소값 |
|``np.max``        |``np.nanmax``        | 최대값 |
|``np.argmin``     |``np.nanargmin``     | 최소값 인덱스 |
|``np.argmax``     |``np.nansrgmax``     | 최대값 인덱스 |
|``np.median``     |``np.nanmedian``     | 중앙값 |
|``np.percentile`` |``np.nanpercentile`` | 요소의 순위 기반 백분위 수 계산 |
|``np.any``        | N/A                 | 요소 중 참이 있는지 평가 |
|``np.all``        | N/A                 | 모든 요소가 참인지 평가 |

### sum(): 합 계산

In [ ]:
a2 =np.random.randint(1, 10, size=(3,3))
print(a2)
print(a2.sum(), np.sum(a2))
print(a2.sum(axis=0), np.sum(a2, axis=0)) # 열병합 합 (결과값의 방향이 행)
print(a2.sum(axis=1), np.sum(a2, axis=1)) # 행방향 합 (결과값의 방향이 열)

[[2 7 3]
 [3 9 4]
 [6 7 4]]
45 45
[11 23 11] [11 23 11]
[12 16 17] [12 16 17]


### cumsum(): 누적 계산

In [ ]:
print(a2)
print(np.cumsum(a2))
print(np.cumsum(a2, axis=0))
print(np.cumsum(a2, axis=1))

[[2 7 3]
 [3 9 4]
 [6 7 4]]
[ 2  9 12 15 24 28 34 41 45]
[[ 2  7  3]
 [ 5 16  7]
 [11 23 11]]
[[ 2  9 12]
 [ 3 12 16]
 [ 6 13 17]]


### prod(): 곱 계산

In [ ]:
print(a2)
print(np.prod(a2))
print(np.prod(a2, axis=0))
print(np.prod(a2, axis=1))

[[2 7 3]
 [3 9 4]
 [6 7 4]]
762048
[ 36 441  48]
[ 42 108 168]


### cumprod(): 누적곱 계산

In [ ]:
print(a2)
print(np.cumprod(a2))
print(np.cumprod(a2, axis=0))
print(np.cumprod(a2, axis=1))

[[2 7 3]
 [3 9 4]
 [6 7 4]]
[     2     14     42    126   1134   4536  27216 190512 762048]
[[  2   7   3]
 [  6  63  12]
 [ 36 441  48]]
[[  2  14  42]
 [  3  27 108]
 [  6  42 168]]


### dot()/matmul(): 점곱/행렬곱 계산

In [ ]:
print(a2)
b2 =np.ones_like(a2)
print(b2)
print(np.dot(a2, b2))
print(np.matmul(a2,b2))

[[2 7 3]
 [3 9 4]
 [6 7 4]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[12 12 12]
 [16 16 16]
 [17 17 17]]
[[12 12 12]
 [16 16 16]
 [17 17 17]]


### mean(): 평균 계산

In [ ]:
print(a2)
print(np.mean(a2))
print(np.mean(a2, axis=0))
print(np.mean(a2, axis=1))

[[2 7 3]
 [3 9 4]
 [6 7 4]]
5.0
[3.66666667 7.66666667 3.66666667]
[4.         5.33333333 5.66666667]


### std(): 표준 편차 계산

In [ ]:
print(a2)
print(np.std(a2))
print(np.std(a2, axis=0))
print(np.std(a2, axis=1))

[[2 7 3]
 [3 9 4]
 [6 7 4]]
2.211083193570267
[1.69967317 0.94280904 0.47140452]
[2.1602469  2.62466929 1.24721913]


### var(): 분산 계산

In [ ]:
print(a2)
print(np.var(a2))
print(np.var(a2, axis=0))
print(np.var(a2, axis=1))

[[2 7 3]
 [3 9 4]
 [6 7 4]]
4.888888888888889
[2.88888889 0.88888889 0.22222222]
[4.66666667 6.88888889 1.55555556]


### min(): 최소값

In [ ]:
print(a2)
print(np.min(a2))
print(np.min(a2, axis=0))
print(np.min(a2, axis=1))

[[2 7 3]
 [3 9 4]
 [6 7 4]]
2
[2 7 3]
[2 3 4]


### max(): 최대값

In [ ]:
print(a2)
print(np.max(a2))
print(np.max(a2, axis=0))
print(np.max(a2, axis=1))

[[2 7 3]
 [3 9 4]
 [6 7 4]]
9
[6 9 4]
[7 9 7]


### argmin(): 최소값 인덱스

In [ ]:
print(a2)
print(np.argmin(a2))
print(np.argmin(a2, axis=0))
print(np.argmin(a2, axis=1))

[[2 7 3]
 [3 9 4]
 [6 7 4]]
0
[0 0 0]
[0 0 2]


### argmax(): 최대값 인덱스

In [ ]:
print(a2)
print(np.argmax(a2))
print(np.argmax(a2, axis=0))
print(np.argmax(a2, axis=1))

[[2 7 3]
 [3 9 4]
 [6 7 4]]
4
[2 1 1]
[1 1 1]


## median(): 중앙

In [ ]:
print(a2)
print(np.median(a2))
print(np.median(a2, axis=0))
print(np.median(a2, axis=1))

[[2 7 3]
 [3 9 4]
 [6 7 4]]
4.0
[3. 7. 4.]
[3. 4. 6.]


### percetile(): 백분위 수

* percentile(a, q, interolation='linear')
  * a배열 요소의 q번째 백분위 수 계산
  * q: 0~100 사이값
  *interpolation: 백분위 수가 데이터i,j(i<j)사이에 있을 때 사용할 보간 방법
    * 'linear': i+(j-i)*fraction, where fractio is the fractional part of index surrounded by i and j
    * 'lower': i
    * 'higher': j
    * 'nearest': i or j, whichever is nearest
    * 'midpoint': (i+j)/2

In [ ]:
a1 = np.arange(1 ,13)
print(a1)
print(np.percentile(a1, [30, 50, 80], interpolation='linear'))
print(np.percentile(a1, [30, 50, 80], interpolation='lower'))
print(np.percentile(a1, [30, 50, 80], interpolation='higher'))
print(np.percentile(a1, [30, 50, 80], interpolation='nearest'))
print(np.percentile(a1, [30, 50, 80], interpolation='midpoint'))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[4.3 6.5 9.8]
[4 6 9]
[ 5  7 10]
[ 4  7 10]
[4.5 6.5 9.5]


In [ ]:
a2 = np.array([[10, 7, 5], [3, 2, 1]])
print(a2)
print(np.percentile(a2, 50))
print(np.percentile(a2, 50, axis=0))
print(np.percentile(a2, 50, axis=1))

[[10  7  5]
 [ 3  2  1]]
4.0
[6.5 4.5 3. ]
[7. 2.]


### any()

In [ ]:
a2 = np.array([[False, False, False],
               [True, True, True],
               [False, True, True]])
print(np.any(a2))
print(np.any(a2, axis=0))
print(np.any(a2, axis=1))

True
[ True  True  True]
[False  True  True]


### all()

In [ ]:
print(np.all(a2))
print(np.all(a2, axis=0))
print(np.all(a2, axis=1))

False
[False False False]
[False  True False]


## 비교연산(Comparison Operators)

| 연산자 | 비교 범용 함수 |
|------|------|
| `==`| `np.equal` |
| `!=`| `np.not_equal` |
| `<` | `np.less` |
| `<=`| `np.less_equal` |
| `>` | `np.greater` |
| `>=`| `np.greater_equal` |

In [ ]:
a1 = np.arange(1, 10)
print(a1)
print(a1 == 5)
print(a1 != 5)
print(a1 < 5)
print(a1 <= 5)
print(a1 > 5)
print(a1 >= 5)

[1 2 3 4 5 6 7 8 9]
[False False False False  True False False False False]
[ True  True  True  True False  True  True  True  True]
[ True  True  True  True False False False False False]
[ True  True  True  True  True False False False False]
[False False False False False  True  True  True  True]
[False False False False  True  True  True  True  True]


## 배열 정렬
  * np.sort(array):정렬된 배열의 복사본 생성, 원본 배열의 변경 없음
  * array.sort(): 원본 배열의 값이 변경됨

In [ ]:
a1 = np.random.randint(1, 10, size=10)
print(np.sort(a1))
print(a1)
print(a1.sort())
print(a1)

[2 3 3 3 3 3 6 7 8 9]
[3 8 3 2 3 7 9 3 3 6]
None
[2 3 3 3 3 3 6 7 8 9]


## 부분 정렬
  * `partition(array, k)`: 배열에서 k개의 작은 값을 선택하여 왼쪽에 배치
    * -k:k개의 큰 값을 오른쪽에 배치

In [ ]:
a1 = np.random.randint(1, 10, size=10)
print(a1)
print(np.partition(a1, 3))
print(np.partition(a1, -3))

[5 5 3 5 1 5 5 1 3 3]
[1 1 3 3 5 5 5 5 3 5]
[1 1 3 3 3 5 5 5 5 5]


| 함수	      | 설명           | 파일 종류        |
|---------------|---------------------|-------------|
|``np.save()``      | NumPy배열 객체 1개를 파일에 저장        | 바이너리 |
|``np.savez()``     | NumPy배열 객체 여러개를 파일에 저장    | 바이너리 |
|``np.load()``      | NumPy배열 저장 파일로부터 객체 로딩  | 바이너리 |
|``np.loadtxt()``   | 텍스트 파일로부터 배열 로딩       | 텍스트 |
|``np.savetxt()``   | 텍스트 파일에 NumPy 배열 객체 저장    | 텍스트 |

In [ ]:
a2 = np.random.randint(1, 10, size=(5,5))
print(a2)
np.save("a", a2)

[[7 9 7 8 8]
 [9 9 7 5 2]
 [7 4 8 1 9]
 [1 2 3 6 2]
 [7 9 3 4 5]]


In [ ]:
ls

a.npy  sample_data/


# 참고문헌

* NumPy, https://numpy.org/
* Jake VanderPlas, "Python Data Science Handbook", O'Reilly
* Wes Mckinney, "Python for Data Analysis", O'Reilly